### ISSUE TITLE
Issue while using bow

### ISSUE THREAD

**Issue by Meszpo** [ProtocolSupport/ProtocolSupportPocketIssues#112]
```
[18:14:21 INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:                     
[18:14:21 WARN]: java.lang.NullPointerException                           
[18:14:21 WARN]:        at protocolsupport.protocol.typeremapper.itemstack
.complex.fromclient.NBTUnStashRemapper.remapTag(NBTUnStashRemapper.java:13
)
[18:14:21 WARN]:        at protocolsupport.protocol.typeremapper.itemstack
.complex.ItemStackNBTComplexRemapper.remap(ItemStackNBTComplexRemapper.jav
a:13)
[18:14:21 WARN]:        at protocolsupport.protocol.typeremapper.itemstack
.complex.ItemStackComplexRemapperRegistry.remapComplex(ItemStackComplexRem
apperRegistry.java:201)
[18:14:21 WARN]:        at protocolsupport.protocol.typeremapper.itemstack
.complex.ItemStackComplexRemapperRegistry.remapFromClient(ItemStackComplex
RemapperRegistry.java:213)
[18:14:21 WARN]:        at protocolsupport.protocol.typeremapper.itemstack
.ItemStackRemapper.remapFromClient(ItemStackRemapper.java:44)
[18:14:21 WARN]:        at protocolsupport.protocol.serializer.ItemStackSe
rializer.readItemStack(ItemStackSerializer.java:101)
[18:14:21 WARN]:        at protocolsupport.protocol.packet.middleimpl.serv
erbound.play.v_pe.GodPacket$InvTransaction.readFromStream(GodPacket.java:1
66)
[18:14:21 WARN]:        at protocolsupport.protocol.packet.middleimpl.serv
erbound.play.v_pe.GodPacket$InvTransaction.access$000(GodPacket.java:125)
[18:14:21 WARN]:        at protocolsupport.protocol.packet.middleimpl.serv
erbound.play.v_pe.GodPacket.readFromClientData(GodPacket.java:55)
[18:14:21 WARN]:        at protocolsupport.protocol.pipeline.version.util.
decoder.AbstractPacketDecoder.decodeAndTransform(AbstractPacketDecoder.jav
a:40)
[18:14:21 WARN]:        at protocolsupport.protocol.pipeline.version.v_pe.
PEPacketDecoder.decode(PEPacketDecoder.java:83)
[18:14:21 WARN]:        at protocolsupport.protocol.pipeline.version.v_pe.
PEPacketDecoder.decode(PEPacketDecoder.java:42)
[18:14:21 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.
channelRead(MessageToMessageDecoder.java:88)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:14:21 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.c
hannelRead(ChannelInboundHandlerAdapter.java:86)
[18:14:21 WARN]:        at protocolsupport.protocol.pipeline.common.RawPac
ketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:14:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fir
eChannelRead(ByteToMessageDecoder.java:310)
[18:14:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fir
eChannelRead(ByteToMessageDecoder.java:297)
[18:14:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.cal
lDecode(ByteToMessageDecoder.java:413)
[18:14:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.cha
nnelRead(ByteToMessageDecoder.java:265)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:14:21 WARN]:        at protocolsupport.protocol.pipeline.common.Simple
ReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:14:21 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadCon
text.channelRead(DefaultChannelPipeline.java:1434)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:14:21 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireCha
nnelRead(DefaultChannelPipeline.java:965)
[18:14:21 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChann
el$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[18:14:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processRe
ady(EpollEventLoop.java:408)
[18:14:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(Epoll
EventLoop.java:308)
[18:14:21 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecu
tor$5.run(SingleThreadEventExecutor.java:884)
[18:14:21 WARN]:        at java.lang.Thread.run(Thread.java:748)          
[18:14:21 INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:                     
[18:14:21 WARN]: java.lang.NullPointerException                           
[18:14:21 WARN]:        at protocolsupport.protocol.typeremapper.itemstack
.complex.fromclient.NBTUnStashRemapper.remapTag(NBTUnStashRemapper.java:13
)
[18:14:21 WARN]:        at protocolsupport.protocol.typeremapper.itemstack
.complex.ItemStackNBTComplexRemapper.remap(ItemStackNBTComplexRemapper.jav
a:13)
[18:14:21 WARN]:        at protocolsupport.protocol.typeremapper.itemstack
.complex.ItemStackComplexRemapperRegistry.remapComplex(ItemStackComplexRem
apperRegistry.java:201)
[18:14:21 WARN]:        at protocolsupport.protocol.typeremapper.itemstack
.complex.ItemStackComplexRemapperRegistry.remapFromClient(ItemStackComplex
RemapperRegistry.java:213)
[18:14:21 WARN]:        at protocolsupport.protocol.typeremapper.itemstack
.ItemStackRemapper.remapFromClient(ItemStackRemapper.java:44)
[18:14:21 WARN]:        at protocolsupport.protocol.serializer.ItemStackSe
rializer.readItemStack(ItemStackSerializer.java:101)
[18:14:21 WARN]:        at protocolsupport.protocol.packet.middleimpl.serv
erbound.play.v_pe.HeldSlot.readFromClientData(HeldSlot.java:20)
[18:14:21 WARN]:        at protocolsupport.protocol.pipeline.version.util.
decoder.AbstractPacketDecoder.decodeAndTransform(AbstractPacketDecoder.jav
a:40)
[18:14:21 WARN]:        at protocolsupport.protocol.pipeline.version.v_pe.
PEPacketDecoder.decode(PEPacketDecoder.java:83)
[18:14:21 WARN]:        at protocolsupport.protocol.pipeline.version.v_pe.
PEPacketDecoder.decode(PEPacketDecoder.java:42)
[18:14:21 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.
channelRead(MessageToMessageDecoder.java:88)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:14:21 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.c
hannelRead(ChannelInboundHandlerAdapter.java:86)
[18:14:21 WARN]:        at protocolsupport.protocol.pipeline.common.RawPac
ketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:14:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fir
eChannelRead(ByteToMessageDecoder.java:310)
[18:14:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.cha
fireChannelRead(AbstractChannelHandlerContext.java:340)                   
[18:14:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fir
eChannelRead(ByteToMessageDecoder.java:310)                               
[18:14:21 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.cha
nnelRead(ByteToMessageDecoder.java:284)                                   
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:362)                 
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:348)                 
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
fireChannelRead(AbstractChannelHandlerContext.java:340)                   
[18:14:21 WARN]:        at protocolsupport.protocol.pipeline.common.Simple
ReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39)          
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:362)                 
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:348)                 
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
fireChannelRead(AbstractChannelHandlerContext.java:340)                   
[18:14:21 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadCon
text.channelRead(DefaultChannelPipeline.java:1434)                        
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:362)                 
[18:14:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.
invokeChannelRead(AbstractChannelHandlerContext.java:348)                 
[18:14:21 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireCha
nnelRead(DefaultChannelPipeline.java:965)                                 
[18:14:21 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChann
el$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)    
[18:14:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processRe
ady(EpollEventLoop.java:408)                                              
[18:14:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(Epoll
EventLoop.java:308)                                                       
[18:14:21 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecu
tor$5.run(SingleThreadEventExecutor.java:884)                             
[18:14:21 WARN]:        at java.lang.Thread.run(Thread.java:748)          
[18:14:21 INFO]: xIgreq lost connection: Internal Exception: io.netty.hand
ler.codec.DecoderException: java.lang.NullPointerException                
[18:14:22 INFO]: xIgreq left the game
```

**Comment by Meszpo** [comment]
MCPE 1.12
Only on Gamemode 0
