### ISSUE TITLE
[PSBungee] Entity remap error in packet ID 39

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ProtocolSupport/ProtocolSupportPocketIssues#48]
```
[14:37:37] [Netty Worker IO Thread #5/INFO]: [MrPowerGamerBR|/10.0.0.30:46984] <-> ServerConnector [sparklypower_survival] has connected
[14:37:38] [Netty Worker IO Thread #5/ERROR]: Entity remap error in packet ID 39
[14:37:38] [Netty Worker IO Thread #5/ERROR]: [/10.0.0.30:46984|MrPowerGamerBR] <-> DownstreamBridge <-> [sparklypower_survival] - encountered exception
java.lang.IndexOutOfBoundsException: writerIndex(0) + minWritableBytes(62) exceeds maxCapacity(61): UnpooledHeapByteBuf(ridx: 0, widx: 0, cap: 61/61)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:288) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:277) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1099) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1092) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1083) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at protocolsupport.protocol.packet.entityrewrite.EntityRewrite.rewrite(EntityRewrite.java:31) ~[?:?]
	at protocolsupport.protocol.packet.handler.EntityRewriteDownstreamBridge.handle(EntityRewriteDownstreamBridge.java:28) ~[?:?]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at protocolsupport.protocol.pipeline.common.LogicHandler.channelRead(LogicHandler.java:27) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

(for just a "sketch" of the issue, I just don't want to lose the stacktrace if I can't get it to happen again)

**Comment by MrPowerGamerBR** [comment]
Fixed by @colinrgodsey 👏
