### ISSUE TITLE
Exception on unmounting (?)

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ProtocolSupport/ProtocolSupportPocketIssues#52]
```
[20:54:26 WARN]: Caused by: io.netty.handler.codec.DecoderException: Unable to transform or read packet data [0, 19, -7, -57, 26, 0, 32, 34, 68, 51, -45, -114, 66, 72, -17, 82, 67, 112, -84, 39, 65, 112, 101, 82, -63, 112, 101, 82, -63, 3, 1, -94, -108, 33]
[20:54:26 WARN]:        at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.throwFailedTransformException(AbstractPacketDecoder.java:53)
[20:54:26 WARN]:        at protocolsupport.protocol.pipeline.version.v_pe.PEPacketDecoder.decode(PEPacketDecoder.java:90)
[20:54:26 WARN]:        at protocolsupport.protocol.pipeline.version.v_pe.PEPacketDecoder.decode(PEPacketDecoder.java:43)
[20:54:26 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[20:54:26 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:54:26 WARN]:        ... 34 more
[20:54:26 WARN]: Caused by: java.lang.NullPointerException
[20:54:26 WARN]:        at protocolsupport.protocol.packet.middleimpl.serverbound.play.v_pe.PositionLook.toNative(PositionLook.java:74)
[20:54:26 WARN]:        at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.decodeAndTransform(AbstractPacketDecoder.java:36)
[20:54:26 WARN]:        at protocolsupport.protocol.pipeline.version.v_pe.PEPacketDecoder.decode(PEPacketDecoder.java:85)
[20:54:26 WARN]:        ... 37 more
```

It *seems* this happens when killing the entity the player was mounted on, but I'm not sure yet

**Comment by Artuto** [comment]
Yeah happened to me too.

**Comment by MrPowerGamerBR** [comment]
Fixed inhttps://github.com/ProtocolSupport/ProtocolSupport/commit/e399a6033bca572106c764e9f8666cff86742a0b 👏
