### ISSUE TITLE
[PSB] Error whilst handling query packet

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupportPocketIssues#53]
This error occurs randomly (not always)

```java
[19:20:59 WARN]: Error whilst handling query packet from /66.228.34.58:60146
java.lang.IllegalStateException: No session!
at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:88) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:26) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at protocolsupport.injector.pe.PEQueryHandler.channelRead(PEQueryHandler.java:56) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at protocolsupport.libs.udpserversocketchannel.channel.UdpChannel.doBeginRead(UdpChannel.java:89) ~[?:?]
at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:847) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1386) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:95) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.ChannelDuplexHandler.read(ChannelDuplexHandler.java:95) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.ChannelOutboundHandlerAdapter.read(ChannelOutboundHandlerAdapter.java:93) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:693) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:673) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1050) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannel.read(AbstractChannel.java:284) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1446) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1424) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by colinrgodsey** [comment]
https://minecraftservers.org/query-ip . IP is from this site. Guessing something flaked out during the query, think i see this one sometimes too

**Comment by Artuto** [comment]
Yeah, however, it happens usually many times on the day...

**Comment by colinrgodsey** [comment]
Hmm, I think the query is just a brittle process. Guess we should maybe just suppress the error? or at least the stack trace?

**Comment by Artuto** [comment]
Maybe, probably is not even worthit to display the error, the owner cant really fix it or anything.

**Comment by colinrgodsey** [comment]
actually yes, this is definitely fixed in my latest commits
