### ISSUE TITLE
Client kicked due to "Too big packet loss (unconfirmed sent packets)" at player respawn

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#78]
I've gotten a recurring issue, which kicks the client, and possibly makes the server unstable as well. 

I get an (almost?) endless repeating list of exceptions starting like this:
```
[11:39:20 WARN]: PEProxy client connection exception occured
[11:39:20 WARN]: io.netty.handler.codec.DecoderException: Too big packet loss (unconfirmed sent packets)
[11:39:20 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[11:39:20 WARN]: 	at protocolsupport.libs.raknetserver.pipeline.raknet.RakNetPacketReliabilityHandler.write(RakNetPacketReliabilityHandler.java:51)
[11:39:20 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
```

It has happened almost always - perhaps even reproducable to 100% (but I'm not sure) - when you respawn after having died. It has also happened on other occasions though, which is a bit worrisome. I have not noticed any other regular pattern though, so maybe starting with repro:ing the respawn-after-death issue, and maybe that will locate and solve the issue that lies behind all those crashes.

**Comment by CtrlAltCuteness** [comment]
Very likely for mid-end Bedrock clients like numerous smartphones that play.
